### ISSUE TITLE
use of zlib 1.0.5 long deprecated

### ISSUE THREAD

**Issue by zboni-gpsw** [awslabs/cloudwatch-api-tracker#1]
I'm unable to `npm install` this project, and it seems to be because the zlib included from package.json is very, very out of date. In fact as long ago as 2014 -- https://github.com/zcbenz/node-gui/issues/18 -- folks were saying the use of zlib is long deprecated.  I'm no node.js developer, what am I missing here?

`$ npm install

> zlib@1.0.5 preinstall /tmp/cloudwatch-api-tracker/nodejs/node_modules/.staging/zlib-6588a348
> node-waf clean || true; node-waf configure build

sh: 1: node-waf: not found
sh: 1: node-waf: not found
cloudwatch-api-tracker@0.1.0 /tmp/cloudwatch-api-tracker/nodejs
└─┬ aws-sdk@2.23.0
  ├─┬ buffer@4.9.1
  │ ├── base64-js@1.2.0
  │ ├── ieee754@1.1.8
  │ └── isarray@1.0.0
  ├── crypto-browserify@1.0.9
  ├── jmespath@0.15.0
  ├── querystring@0.2.0
  ├── sax@1.1.5
  ├─┬ url@0.10.3
  │ └── punycode@1.3.2
  ├── uuid@3.0.0
  ├── xml2js@0.4.15
  └─┬ xmlbuilder@2.6.2
    └── lodash@3.5.0

npm WARN cloudwatch-api-tracker@0.1.0 license should be a valid SPDX license expression
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! zlib@1.0.5 preinstall: `node-waf clean || true; node-waf configure build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the zlib@1.0.5 preinstall script 'node-waf clean || true; node-waf configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zlib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf clean || true; node-waf configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zlib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zlib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/cloudwatch-api-tracker/nodejs/npm-debug.log
ubuntu@ip-11-0-9-200:/tmp/cloudwatch-api-tracker/nodejs$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
ubuntu@ip-11-0-9-200:/tmp/cloudwatch-api-tracker/nodejs$ npm --version
4.1.2
ubuntu@ip-11-0-9-200:/tmp/cloudwatch-api-tracker/nodejs$ node --version
v7.7.1
ubuntu@ip-11-0-9-200:/tmp/cloudwatch-api-tracker/nodejs$ which node-waf
ubuntu@ip-11-0-9-200:/tmp/cloudwatch-api-tracker/nodejs$`

**Comment by homingli** [comment]
Neither of the dependencies in package.json are really necessary to run this function on AWS Lambda. So go ahead and give that a try and see if you still have issues. I'll update the code to reflect this.

Please also note that you are running node v7 while AWS current only supports node 4.3 runtime. See: https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html
